### ISSUE TITLE
update IEM project page

### ISSUE THREAD

**Issue by brucecrevensten** [ua-snap/snap-www#130]

**Comment by bamelegari** [comment]
I received an email a while ago from Amy containing what the description should be etc. for the new IEM page but it also had a list of stuff that should be available on the page (downloads, etc.) which I don't have copies of. It's also simply been a while since I've heard anything regarding what's supposed to be here. anyone have any words on specifics?

**Comment by brucecrevensten** [comment]
coordinate with Craig, Carolyn and/or Amy, please.

On Mon, Mar 11, 2013 at 4:02 PM, bamelegari notifications@github.comwrote:

> I received an email a while ago from Amy containing what the description
> should be etc. for the new IEM page but it also had a list of stuff that
> should be available on the page (downloads, etc.) which I don't have copies
> of. It's also simply been a while since I've heard anything regarding
> what's supposed to be here. anyone have any words on specifics?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ua-snap/snap-www/issues/130#issuecomment-14750957
> .

## 

*Bruce Crevensten, Programmer
*
(ACUASI) Alaska Center for UAS Integration
(SNAP) Scenarios Network for Alaska & Arctic Planning
www.snap.uaf.edu

**Comment by takurkowski** [comment]
Correction...Craig, Kristin, and Amy.

Tom
- sent using a tiny keyboard, please excuse the brevity

**Comment by bamelegari** [comment]
closing this issue because there is a duplicate with more concrete details https://github.com/ua-snap/snap-www/issues/141
